// sample5.cpp : Defines the entry point for the console application.
//

extern "C" 
{
	#include "lua.h"
	#include "lualib.h"
	#include "lauxlib.h"
};

#include "luatinker.h"

void show_error(const char* error)
{
	printf("_ALERT -> %s\n", error);
}

//int main()
//{
//	// Lua 를 초기화 한다.
//	lua_State* L = luaL_newstate();
//
//	// Lua 기본 함수들을 로드한다.- print() 사용
//    luaL_openlibs(L);
//
//
//	// lua_State* 가 갖고있는 현재의 스택을 보여준다.
//	printf("%s\n","-------------------------- current stack");
//	luatinker::enum_stack(L);
//
//	// 스택에 1을 밀어넣는다.
//	lua_pushnumber(L, 1);
//
//	// 현재 스택의 내용을 다시 출력한다.
//	printf("%s\n","-------------------------- stack after push '1'");
//	luatinker::enum_stack(L);
//
//
//	// sample5.lua 파일을 로드/실행한다.
//	luatinker::dofile(L, "sample5.lua");
//
//	// test_error() 함수를 호출한다.
//	// test_error() 는 실행중 test_error_3() 호출을 시도하다 에러를 발생시킨다.
//	// 함수 호출중 발생한 에러는 printf()를 통해서 출력된다.
//	printf("%s\n","-------------------------- calling test_error()");
//	luatinker::call<void>(L, "test_error");
//
//	// test_error_3()는 존재하지 않는 함수이다. 호출 자체가 실패한다.
//	printf("%s\n","-------------------------- calling test_error_3()");
//	luatinker::call<void>(L, "test_error_3");
//
//	// printf() 대신 유저가 제공하는 에러 출력 루틴을 사용할 수 있다.
//	// 이 에러처리 함수는1개의 루아 문자열로 발생한 에러를 전달하게 된다.
//	// C++ 에서 등록할 경우 void function(const char*) 형태가 적합하다.
//	luatinker::def(L, "_ALERT", show_error);
//
//	luatinker::call<void>(L, "_ALERT", "test !!!");
//
//	// test_error() 함수를 호출한다.
//	// 함수 호출중 발생한 에러는 Lua에 등록된 _ALERT()를 통해서 출력된다.
//	printf("%s\n","-------------------------- calling test_error()");
//	luatinker::call<void>(L, "test_error");
//
//
//	// 프로그램 종료
//	lua_close(L);
//
//	return 0;
//}

